buildCode:
  - '**/*.gradle'
  - '**/*.gradle.kts'
  - '**/*.toml'
  - '**/gradle.properties'
  - 'gradle/**'
  - 'buildSrc/**'
  - 'buildSrc-fork/**'
  - 'androidx-settings-plugins-fork/**'
  - 'gradlew'
  - 'gradlew.bat'
  - '.github/workflows/build-code.yml'
  - '.github/path-filter.yml'

# Change with sourceSetsUnknown
sourceSetsNative:
  - '**/iosMain/**'
  - '**/iosTest/**'
  - '**/darwinMain/**'
  - '**/darwinTest/**'
  - '**/nativeMain/**'
  - '**/nativeTest/**'
  - '**/uikitMain/**'
  - '**/uikitTest/**'
  - '**/uikitInstrumentedTest/**'
  - '**/appleMain/**'
  - '**/appleTest/**'
  - '**/macosMain/**'
  - '**/macosTest/**'
  - '**/tvosMain/**'
  - '**/tvosTest/**'
  - '**/watchosMain/**'
  - '**/watchosTest/**'
  - '**/linuxMain/**'
  - '**/linuxTest/**'
  - '**/mingwMain/**'
  - '**/mingwTest/**'

# Change with sourceSetsUnknown
sourceSetsWeb:
  - '**/webMain/**'
  - '**/webTest/**'
  - '**/jsMain/**'
  - '**/jsTest/**'
  - '**/jsWasmMain/**'
  - '**/jsWasmTest/**'
  - '**/wasmJsMain/**'
  - '**/wasmJsTest/**'

# Change with sourceSetsUnknown
sourceSetsDesktop:
  - '**/jvmMain/**'
  - '**/jvmTest/**'
  - '**/desktopMain/**'
  - '**/desktopTest/**'

# Change with sourceSetsNative, sourceSetsWeb, sourceSetsDesktop
# A copy because of simplicity and a low chance of mistakes
sourceSetsUnknown:
  - '**'
  - '!**/iosMain/**'
  - '!**/iosTest/**'
  - '!**/darwinMain/**'
  - '!**/darwinTest/**'
  - '!**/nativeMain/**'
  - '!**/nativeTest/**'
  - '!**/uikitMain/**'
  - '!**/uikitTest/**'
  - '!**/uikitInstrumentedTest/**'
  - '!**/appleMain/**'
  - '!**/appleTest/**'
  - '!**/macosMain/**'
  - '!**/macosTest/**'
  - '!**/tvosMain/**'
  - '!**/tvosTest/**'
  - '!**/watchosMain/**'
  - '!**/watchosTest/**'
  - '!**/linuxMain/**'
  - '!**/linuxTest/**'
  - '!**/mingwMain/**'
  - '!**/mingwTest/**'

  - '!**/webMain/**'
  - '!**/webTest/**'
  - '!**/jsMain/**'
  - '!**/jsTest/**'
  - '!**/jsWasmMain/**'
  - '!**/jsWasmTest/**'
  - '!**/wasmJsMain/**'
  - '!**/wasmJsTest/**'

  - '!**/jvmMain/**'
  - '!**/jvmTest/**'
  - '!**/desktopMain/**'
  - '!**/desktopTest/**'
