/**
 * This file was created using the `create_project.py` script located in the
 * `<AndroidX root>/development/project-creator` directory.
 *
 * Please use that script when creating a new project, rather than copying an existing project and
 * modifying its settings.
 */
import androidx.build.PlatformIdentifier
import androidx.build.SoftwareType

plugins {
    id("AndroidXPlugin")
    id("JetBrainsAndroidXPlugin")
}

androidXMultiplatform {
    redirect("androidx.annotation") {
        ios()
        js()
        jvm()
        linux()
        mac()
        mingwX64()
        tvos()
        wasmJs()
        watchos()
    }

    defaultPlatform(PlatformIdentifier.JVM)
}

androidx {
    name = "Annotation"
    type = SoftwareType.PUBLISHED_LIBRARY
    inceptionYear = "2013"
    description = "Provides source annotations for tooling and readability."
}
