apply from: "../shared.gradle"
apply plugin: "java-gradle-plugin"

dependencies {
    implementation(project(":public"))
    implementation(project(":imports:benchmark-gradle-plugin"))
    implementation(project(":imports:inspection-gradle-plugin"))
    implementation(project(":imports:stableaidl-gradle-plugin"))
    implementation(project(":imports:binary-compatibility-validator"))
}


/* JB FORK ONLY SECTION */
// We disable these files since the code there is not used in the fork,
// but it complicates merges (until we update to the same AGP and dackka versions as in the androidx-main)
sourceSets {
    main {
        kotlin {
            exclude '**/DackkaTask.kt'
            exclude '**/AndroidXDocsImplPlugin.kt'
        }
    }
}
/* END SECTION */