/**
 * This file was created using the `createProject` gradle task (./gradlew createProject)
 *
 * Please use the task when creating a new project, rather than copying an existing project and
 * modifying its settings.
 */
plugins {
    id("AndroidXPlugin")
    id("com.android.application")
    //id("com.android.experimental.built-in-kotlin")
    id("org.jetbrains.kotlin.android")
}

dependencies {
    api(libs.jspecify)
    implementation(project(":appcompat:appcompat"))
    implementation("androidx.core:core:1.15.0")
}

android {
    compileSdk = 35
    defaultConfig {
        vectorDrawables.useSupportLibrary = true
    }
    lint {
        disable.add("WrongThread")
    }
    namespace = "com.example.android.appcompat"
}
