name: Compose Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - jb-main

jobs:
  compose-ios-instrumented-tests-iphone-14-16-0:
    runs-on: macos-13-xlarge
    name: Compose iOS Instrumented Tests - iPhone 14 (16.0)
    env:
      GRADLE_OPTS: -Xmx12g -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Run iOS Instrumented Tests
        timeout-minutes: 30
        uses: ./.github/actions/ios-instrumented-tests
        with:
          simulator-name: 'iPhone 14'
          simulator-version: '16.0'

  compose-ios-instrumented-tests-ipad-16-0:
    runs-on: macos-13-xlarge
    name: Compose iOS Instrumented Tests - iPad Pro (16.0)
    env:
      GRADLE_OPTS: -Xmx12g -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Run iOS Instrumented Tests
        timeout-minutes: 30
        uses: ./.github/actions/ios-instrumented-tests
        with:
          simulator-name: 'iPad Pro (11-inch) (4th generation)'
          simulator-version: '16.0'

