name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - jb-main
      - integration

env:
  # TODO: https://youtrack.jetbrains.com/issue/CMP-9497/Investgate-CfW-tests-flakiness-with-enabled-gradle-configuration-cache-on-CI
  # Web Tests require running additional processes: karma in node, browser;
  # To reduce the memory pressure, we change some defaults:
  GRADLE_WEB_TESTS_FLAGS: >-
    --no-daemon --stacktrace --no-parallel --no-configuration-cache
    -Dorg.gradle.jvmargs="-Xmx6g -XX:+UseParallelGC"
    -Porg.gradle.workers.max=1

jobs:
  compose-desktop-tests:
    runs-on: ubuntu-24.04
    name: Desktop
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Prerequisites
        uses: ./.github/actions/setup-prerequisites

      - name: Setup Window Manager
        run: sudo apt-get update && sudo apt-get install -y xvfb openbox x11-utils

      - name: Start X Server
        run: |
          sudo Xvfb :1 -screen 0 1920x1080x24 -extension RANDR +extension GLX &
          export DISPLAY=:1
          until xdpyinfo >/dev/null 2>&1; do sleep 0.1; done
          openbox &
          until xprop -root _NET_SUPPORTING_WM_CHECK >/dev/null 2>&1; do sleep 0.1; done
          echo "DISPLAY=:1.0" >> $GITHUB_ENV

      - name: Run Desktop
        run: |
          ./gradlew testDesktop \
            --no-daemon --stacktrace

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshot-tests
          path: |
            golden/**/*_actual.png
            golden/**/*_diff.png

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "out/**/build/test-results/**/TEST-*.xml"
        if: always()
